version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user 
      POSTGRES_DB: inventory
      POSTGRES_PASSWORD: 123456
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d inventory"]
      interval: 5s
      timeout: 10s
      retries: 5
  api:
    build:
     context: .
     dockerfile: Dockerfile
    env_file: dev.env
    ports:
      - "8080:8080"
    depends_on: 
     postgres:
       condition: service_healthy
  redis:
    image: redis:alpine
    command: redis-server --requirepass 12345
    ports:
      - "6379:6379"
